### ISSUE TITLE
Nested references aren't processed

### ISSUE THREAD

**Issue by emtou** [zeelot/kohana-dependencies#2]
Points in references' arguments invalidate regexp matching, so the examples in the README don't work as expected.
### Quick fix :

in **classes/kohana/dependency/reference.php**, replace :

``` php5
abstract class Kohana_Dependency_Reference {
    const KEY_FORMAT = '[0-9a-zA-Z_-]+([0-9a-zA-Z_-]+)*';
```

with :

``` php5
abstract class Kohana_Dependency_Reference {
    const KEY_FORMAT = '[0-9a-zA-Z_-]+(\.[0-9a-zA-Z_-]+)*';
```

**Comment by jeremeamia** [comment]
Thanks again. I must have just missed that, because that was definitely what I intended the regex to be.
